# Generated by Django 4.2 on 2023-08-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_info', models.TextField()),
                ('diet_preferences', models.TextField()),
                ('sleep_patterns', models.TextField()),
                ('emotion_status', models.TextField()),
                ('recommendation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
