# Generated by Django 4.2 on 2023-08-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0002_healthdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.PositiveIntegerField()),
                ('protein', models.PositiveIntegerField()),
                ('carbohydrates', models.PositiveIntegerField()),
                ('fats', models.PositiveIntegerField()),
                ('recommendation', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
