# Generated by Django 4.2 on 2023-08-24 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_consume_id_alter_food_id_alter_sleeppattern_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='consume',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
